all:
  children:
    servers:
      hosts:
        bellamy:
          ansible_host: bellamy # bellamy
        prod_srv_2:
          ansible_host: 100.81.26.84 # finn
    # databases:
    #   hosts:
    #
