---
- name: Backup NixOS services to MinIO
  hosts: bellamy #  hosts: bellamy,other-host,another-host
  become: yes
  gather_facts: true

  tasks:
    - name: Run Backup Role
      ansible.builtin.import_role:
        name: backup
      tags: backup
